name: update_resources
on:
  schedule:
    - cron: '0 */24 * * *'
  repository_dispatch:
    types: [update_resources]
jobs:
  update_history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch resources changes
        id: fetch_changes
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          wget --mirror --tries=100 --continue 'http://downloader1.meitangdehulu.com:22943' && cd './downloader1.meitangdehulu.com:22943' && rm 'index.html' && ls && mv * ../ && cd ../ && rm 'downloader1.meitangdehulu.com:22943' && ls
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo '::set-output name=changed::false'
          else
            # Changes detected
            echo '::set-output name=changed::true'
            git commit -m "Update resources（`date +'%Y-%m-%d'`）

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Push changes
        if: steps.fetch_changes.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
