name: update_resources
# on:
#  schedule:
#    # - cron: '0 7 * * *'
#    - cron: '5 */1 * * *'
#  repository_dispatch:
#     types: [update_resources]

on: [push, pull_request]

jobs:
  update_resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch resources changes
        id: fetch_changes
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          wget --continue -d -N --no-proxy --no-use-server-timestamps -t 50 -i 'http://downloader1.meitangdehulu.com:22943/'
          rm 'index.html'
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo '::set-output name=changed::false'
          else
            # Changes detected
            echo '::set-output name=changed::true'
            git commit -m "Update resources

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Push changes
        if: steps.fetch_changes.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
  update_resources-gitcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch resources changes
        id: fetch_changes
        shell: bash
        run: |
          git rm --cached I18nUpdateMod-resources
      - name: Push changes
        if: steps.fetch_changes.outputs.changed == 'true'
        shell: bash
        run: |
          echo 'https://gitcode.net/chearlai/I18nUpdateMod-resources'
