name: update_resources
on:
 pull_request:
    branches: [main]
 push:
    branches: [main]
    paths: 
      - '.github/workflows/update.yml'
    # 定时触发
  schedule:
    # 每1小时获取一次
    - cron: '0 */2 * * *'
 repository_dispatch:
   types: [update_resources]

jobs:
  update_resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set time
        shell: bash
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Fetch resources changes
        id: fetch_changes
        shell: bash
        run: |
          echo '====================flushdns======================='
          sudo './flashdns.sh'
          echo '==================================================='
          cd './files'
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          echo '=================flashresources===================='
          wget --no-dns-cache --random-wait -d -N -T 60 -t 30 -i 'http://downloader1.meitangdehulu.com:22943/'
          echo '==================================================='
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            git commit -m "Update resources（`date '+%Y-%m-%d %H:%M:%S'`）

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Push changes
        if: steps.fetch_changes.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
