name: Update resources

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths: 
      - '.github/workflows/update.yml'
  schedule:
    - cron: '0 20-22 * * *' # Every hour, between 20:00 and 22:59, every day
  repository_dispatch:
    types: [update_resources]

jobs:
  update_resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set time
        shell: bash
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: flash dns
        shell: bash
        run: |
          sudo './flashdns.sh'
      - name: check updata
        id: check_updata
        shell: bash
        run: |
          echo '========================== 检查区 ==========================='
          rm index.txt
          wget --header='This_is_GitHub-Action_bot：https://github.com/zkitefly/TranslationPackMirror' --no-dns-cache --random-wait --continue -d -T 60 -t 30 -O index.txt "http://downloader1.meitangdehulu.com:22943/"
          if md5sum -c --quiet 'md5.txt'; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            md5sum index.txt > md5.txt
          fi
          echo '============================================================'
      - name: Fetch resources changes
        if: steps.check_updata.outputs.changed == 'true'
        id: fetch_changes
        shell: bash
        run: |
          ./1.sh
      - name: Commit
        if: steps.check_updata.outputs.changed == 'true'
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update resources（`date '+%Y-%m-%d %H:%M:%S'`）$GITHUB_RUN_ID

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
      - name: Push changes
        if: steps.check_updata.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
